### ISSUE TITLE
It does not work at least on Windows 10 (SSH server)

### ISSUE THREAD

**Issue by HeavyBro1337** [progrium/tview-ssh#1]
I get the error at screen.Init() "no suitable screen available".
What possibly go wrong? I've cloned your project and did not change anything but host key and port.

**Comment by progrium** [comment]
You'll have to be more specific about how you're running it. PTY are probably POSIX specific, so windows would have to use it in a context that provides that. Linux subsystem or whatever, I don't use Windows that way.

**Comment by Virviil** [comment]
Doesnt work for me either on mac.

Mb you can provide docker at least for host machine?

**Comment by progrium** [comment]
Mb you can provide me with the error you're getting on Mac since I can't do *anything* with "it doesn't work"

**Comment by Virviil** [comment]
I get empty screen in terminal after ssh. With no errors on the server side

**Comment by Virviil** [comment]
@progrium Attaching an asciicast.

It was impossible to exit ssh session from client side, so i've terminated a server after several seconds.
As you see, output continued to come into terminal.
[tmpce38gkqn-ascii.cast.zip](https://github.com/progrium/tview-ssh/files/13111795/tmpce38gkqn-ascii.cast.zip)

**Comment by brodo** [comment]
I had the same problem and fixed it by deleting

```
if err := screen.Init(); err != nil {
	fmt.Fprintln(sess.Stderr(), "unable to init screen:", err)
	return
}
```

**Comment by HeavyBro1337** [comment]
I solved by using docker or wsl
